### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aledbf** [dodevops/k8s-ingress-nginx-hardening#1]
Hi, Is there any interest in adding the guide in the [ingress-nginx docs](https://github.com/kubernetes/ingress-nginx/tree/master/docs)?
(as a guide in the https://kubernetes.github.io/ingress-nginx/deploy/ section)

**Comment by timdeluxe** [comment]
@aledbf 
Sure, however i got different feedback here: https://github.com/nginxinc/kubernetes-ingress/issues/887#issuecomment-634372209
What is the best approach now?

**Comment by aledbf** [comment]
@timdeluxe well, that is a different ingress controller :)

You can see a comparison here https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md

My question is for https://github.com/kubernetes/ingress-nginx - the community project, not the one from **NGINX Inc.**

(also, the guide only points to the community-driven project)

**Comment by aledbf** [comment]
> Sure, however i got different feedback here: nginxinc/kubernetes-ingress#887 (comment)

I think the guide is a useful starting point for those interested in hardening/preparing for a production setup.
From the guide itself, the defaults we have now are mostly ok. For those that need an adjustment, we could review the current defaults (these are inherited from nginx configuration defaults).

**Comment by timdeluxe** [comment]
Oh, thanks for explaining.

So best approach now would be:

1. create a PR with this document against https://github.com/kubernetes/ingress-nginx/tree/master/docs
2. Once PR is accepted and merged
 a) remove this repo
 b) Update https://github.com/nginxinc/kubernetes-ingress/issues/887 with hint to new location

Correct?

**Comment by aledbf** [comment]
> Correct?

yes

**Comment by aledbf** [comment]
@timdeluxe by the way, thank you for working on this guide

**Comment by timdeluxe** [comment]
> by the way, thank you for working on this guide

you are welcome, i needed to do it anyway due to customer request and i like the open-source spirit, so i published it, because it might be useful for others. :)

**Comment by aledbf** [comment]
For the PR:

- add a new file `docs/hardening-guide.md` with the guide
- add a new line after https://github.com/kubernetes/ingress-nginx/blob/master/mkdocs.yml#L48
`- Hardening guide: "hardening-guide.md"`
- test the change locally running `make live-docs`
 
**Note:** the names I used are just examples, name the file and link as you want

**Comment by timdeluxe** [comment]
This has now be implemented/merged in upstream: https://kubernetes.github.io/ingress-nginx/deploy/hardening-guide/
